name: Lint and test
on:
  push:
    branches: [develop]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install
        run: yarn

      - name: tsc + prettier
        run: yarn lint
